// Version 0.0.1 built 241118
// DOF Studio
// Providing a colorful command line output
//

#include <iostream>
#include <string>
#include <type_traits>
#include <sstream>

#include "Colorful.hpp"


#ifdef COLORFUL_H

#ifdef _WIN32
#include <windows.h>
#pragma once
#endif


template<typename _TypeChar = CHAR>
using Color = ColorFall<_TypeChar>;


namespace ColorPresets
{
    
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> reset = Color<_TypeChar>(Color<_TypeChar>::ColorCode::RESET);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> color_reset = Color<_TypeChar>(Color<_TypeChar>::ColorCode::RESET);

    
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> black = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_BLACK);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> red = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_RED);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> green = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_GREEN);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> yellow = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_YELLOW);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> blue = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_BLUE);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> magenta = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_MAGENTA);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> cyan = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_CYAN);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_gray = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_GRAY);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> dark_gray = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_DARK_GRAY);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_red = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_RED);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_green = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_GREEN);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_yellow = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_YELLOW);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_blue = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_BLUE);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_magenta = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_MAGENTA);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> light_cyan = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_LIGHT_CYAN);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> white = Color<_TypeChar>(Color<_TypeChar>::ColorCode::FG_WHITE);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_blue = Color<_TypeChar>(31, 119, 180);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_orange = Color<_TypeChar>(255, 127, 14);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_green = Color<_TypeChar>(44, 160, 44);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_red = Color<_TypeChar>(214, 39, 40);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_purple = Color<_TypeChar>(148, 103, 189);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_brown = Color<_TypeChar>(140, 86, 75);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_pink = Color<_TypeChar>(227, 119, 194);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_gray = Color<_TypeChar>(127, 127, 127);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_yellow = Color<_TypeChar>(188, 189, 34);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ggplot2_cyan = Color<_TypeChar>(23, 190, 207);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_red = Color<_TypeChar>(244, 67, 54);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_pink = Color<_TypeChar>(233, 30, 99);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_purple = Color<_TypeChar>(156, 39, 176);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_deep_purple = Color<_TypeChar>(103, 58, 183);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_indigo = Color<_TypeChar>(63, 81, 181);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_blue = Color<_TypeChar>(33, 150, 243);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_light_blue = Color<_TypeChar>(3, 169, 244);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_cyan = Color<_TypeChar>(0, 188, 212);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_teal = Color<_TypeChar>(0, 150, 136);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_green = Color<_TypeChar>(76, 175, 80);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_light_green = Color<_TypeChar>(139, 195, 74);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_lime = Color<_TypeChar>(205, 220, 57);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_yellow = Color<_TypeChar>(255, 235, 59);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_amber = Color<_TypeChar>(255, 193, 7);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_orange = Color<_TypeChar>(255, 152, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_deep_orange = Color<_TypeChar>(255, 87, 34);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_brown = Color<_TypeChar>(121, 85, 72);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_gray = Color<_TypeChar>(158, 158, 158);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> material_blue_gray = Color<_TypeChar>(96, 125, 139);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> alice_blue = Color<_TypeChar>(240, 248, 255);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> coral = Color<_TypeChar>(255, 127, 80);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> dark_salmon = Color<_TypeChar>(233, 150, 122);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> medium_spring_green = Color<_TypeChar>(0, 250, 154);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> slate_blue = Color<_TypeChar>(106, 90, 205);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> tomato = Color<_TypeChar>(255, 99, 71);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> orchid = Color<_TypeChar>(218, 112, 214);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pantone_living_coral = Color<_TypeChar>(255, 111, 97); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pantone_classic_blue = Color<_TypeChar>(15, 76, 129); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pantone_illuminating = Color<_TypeChar>(245, 223, 77); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pantone_ultimate_gray = Color<_TypeChar>(147, 149, 151); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pantone_veri_peri = Color<_TypeChar>(102, 103, 171); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_maroon = Color<_TypeChar>(128, 0, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_navy = Color<_TypeChar>(0, 0, 128);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_forest_green = Color<_TypeChar>(34, 139, 34);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_olive = Color<_TypeChar>(128, 128, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_teal = Color<_TypeChar>(0, 128, 128);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_fuchsia = Color<_TypeChar>(255, 0, 255);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> web_safe_aqua = Color<_TypeChar>(0, 255, 255);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> rose_gold = Color<_TypeChar>(183, 110, 121);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> champagne = Color<_TypeChar>(247, 231, 206);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> lavender = Color<_TypeChar>(230, 230, 250);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> charcoal = Color<_TypeChar>(54, 69, 79);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> mint_green = Color<_TypeChar>(152, 255, 152);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> peach = Color<_TypeChar>(255, 218, 185);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> sky_blue = Color<_TypeChar>(135, 206, 235);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> lemon_chiffon = Color<_TypeChar>(255, 250, 205);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> golden_rod = Color<_TypeChar>(218, 165, 32);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> royal_blue = Color<_TypeChar>(65, 105, 225);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> midnight_blue = Color<_TypeChar>(25, 25, 112);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> forest_green = Color<_TypeChar>(34, 139, 34);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> sea_green = Color<_TypeChar>(46, 139, 87);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> dodger_blue = Color<_TypeChar>(30, 144, 255);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> firebrick = Color<_TypeChar>(178, 34, 34);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> indian_red = Color<_TypeChar>(205, 92, 92);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> hot_pink = Color<_TypeChar>(255, 105, 180);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> deep_sky_blue = Color<_TypeChar>(0, 191, 255);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> medium_violet_red = Color<_TypeChar>(199, 21, 133);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> deep_pink = Color<_TypeChar>(255, 20, 147);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> lime_green = Color<_TypeChar>(50, 205, 50);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pale_turquoise = Color<_TypeChar>(175, 238, 238);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> light_coral = Color<_TypeChar>(240, 128, 128);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> light_sea_green = Color<_TypeChar>(32, 178, 170);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> pale_violet_red = Color<_TypeChar>(219, 112, 147);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> thistle = Color<_TypeChar>(216, 191, 216);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> sienna = Color<_TypeChar>(160, 82, 45);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> peru = Color<_TypeChar>(205, 133, 63);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> turquoise = Color<_TypeChar>(64, 224, 208);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> steel_blue = Color<_TypeChar>(70, 130, 180);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> burly_wood = Color<_TypeChar>(222, 184, 135);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cadet_blue = Color<_TypeChar>(95, 158, 160);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> salmon = Color<_TypeChar>(250, 128, 114);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> dark_olive_green = Color<_TypeChar>(85, 107, 47);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> dark_orange = Color<_TypeChar>(255, 140, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> golden_yellow = Color<_TypeChar>(255, 223, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> vivid_tangerine = Color<_TypeChar>(255, 160, 137);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> amethyst = Color<_TypeChar>(153, 102, 204);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> raspberry = Color<_TypeChar>(227, 11, 92);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> electric_lime = Color<_TypeChar>(204, 255, 0);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> neon_carrot = Color<_TypeChar>(255, 163, 67);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> burnt_sienna = Color<_TypeChar>(233, 116, 81); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ultramarine_blue = Color<_TypeChar>(18, 10, 143); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> vermilion = Color<_TypeChar>(227, 66, 52); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> ochre = Color<_TypeChar>(204, 119, 34); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> phthalo_green = Color<_TypeChar>(18, 53, 36); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cerulean_blue = Color<_TypeChar>(42, 82, 190); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> alizarin_crimson = Color<_TypeChar>(227, 38, 54); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cadmium_yellow = Color<_TypeChar>(255, 246, 0); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cobalt_blue = Color<_TypeChar>(0, 71, 171); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> indigo = Color<_TypeChar>(75, 0, 130); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> viridian = Color<_TypeChar>(64, 130, 109); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> titanium_white = Color<_TypeChar>(252, 252, 252); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> paynes_gray = Color<_TypeChar>(83, 104, 120); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> prussian_blue = Color<_TypeChar>(0, 49, 83); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> carmine = Color<_TypeChar>(150, 0, 24); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> lapis_lazuli = Color<_TypeChar>(38, 97, 156); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> rose_madder = Color<_TypeChar>(227, 130, 130); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> emerald_green = Color<_TypeChar>(80, 200, 120); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> sap_green = Color<_TypeChar>(80, 128, 70); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> buff = Color<_TypeChar>(240, 220, 130); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> mars_violet = Color<_TypeChar>(150, 75, 108); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> yellow_ochre = Color<_TypeChar>(221, 176, 0); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cobalt_turquoise = Color<_TypeChar>(72, 191, 145); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> manganese_blue = Color<_TypeChar>(3, 169, 244); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> quinacridone_magenta = Color<_TypeChar>(142, 58, 89); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> indian_yellow = Color<_TypeChar>(227, 168, 87); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> naples_yellow = Color<_TypeChar>(250, 218, 94); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> venetian_red = Color<_TypeChar>(200, 8, 21); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> smalt = Color<_TypeChar>(0, 51, 153); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> lavender_blush = Color<_TypeChar>(255, 240, 245); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> sepia = Color<_TypeChar>(112, 66, 20); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> malachite_green = Color<_TypeChar>(11, 218, 81); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> venetian_blue = Color<_TypeChar>(60, 100, 160); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> caput_mortuum = Color<_TypeChar>(89, 39, 32); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> verdigris = Color<_TypeChar>(67, 179, 174); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> cobalt_violet = Color<_TypeChar>(145, 33, 158); 

    
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_black = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_BLACK, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_red = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_RED, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_green = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_GREEN, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_yellow = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_YELLOW, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_blue = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_BLUE, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_magenta = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_MAGENTA, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_cyan = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_CYAN, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_gray = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_GRAY, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_dark_gray = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_DARK_GRAY, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_red = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_RED, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_green = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_GREEN, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_yellow = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_YELLOW, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_blue = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_BLUE, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_magenta = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_MAGENTA, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_light_cyan = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_LIGHT_CYAN, ColorType::BG);
    template<typename _TypeChar = CHAR>
    constexpr Color<_TypeChar> bg_white = Color<_TypeChar>(Color<_TypeChar>::ColorCode::BG_WHITE, ColorType::BG);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_blue = Color<_TypeChar>(31, 119, 180, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_orange = Color<_TypeChar>(255, 127, 14, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_green = Color<_TypeChar>(44, 160, 44, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_red = Color<_TypeChar>(214, 39, 40, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_purple = Color<_TypeChar>(148, 103, 189, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_brown = Color<_TypeChar>(140, 86, 75, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_pink = Color<_TypeChar>(227, 119, 194, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_gray = Color<_TypeChar>(127, 127, 127, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_yellow = Color<_TypeChar>(188, 189, 34, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ggplot2_cyan = Color<_TypeChar>(23, 190, 207, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_red = Color<_TypeChar>(244, 67, 54, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_pink = Color<_TypeChar>(233, 30, 99, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_purple = Color<_TypeChar>(156, 39, 176, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_deep_purple = Color<_TypeChar>(103, 58, 183, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_indigo = Color<_TypeChar>(63, 81, 181, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_blue = Color<_TypeChar>(33, 150, 243, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_light_blue = Color<_TypeChar>(3, 169, 244, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_cyan = Color<_TypeChar>(0, 188, 212, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_teal = Color<_TypeChar>(0, 150, 136, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_green = Color<_TypeChar>(76, 175, 80, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_light_green = Color<_TypeChar>(139, 195, 74, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_lime = Color<_TypeChar>(205, 220, 57, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_yellow = Color<_TypeChar>(255, 235, 59, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_amber = Color<_TypeChar>(255, 193, 7, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_orange = Color<_TypeChar>(255, 152, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_deep_orange = Color<_TypeChar>(255, 87, 34, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_brown = Color<_TypeChar>(121, 85, 72, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_gray = Color<_TypeChar>(158, 158, 158, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_material_blue_gray = Color<_TypeChar>(96, 125, 139, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_alice_blue = Color<_TypeChar>(240, 248, 255, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_coral = Color<_TypeChar>(255, 127, 80, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_dark_salmon = Color<_TypeChar>(233, 150, 122, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_medium_spring_green = Color<_TypeChar>(0, 250, 154, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_slate_blue = Color<_TypeChar>(106, 90, 205, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_tomato = Color<_TypeChar>(255, 99, 71, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_orchid = Color<_TypeChar>(218, 112, 214, ColorType::BG);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pantone_living_coral = Color<_TypeChar>(255, 111, 97, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pantone_classic_blue = Color<_TypeChar>(15, 76, 129, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pantone_illuminating = Color<_TypeChar>(245, 223, 77, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pantone_ultimate_gray = Color<_TypeChar>(147, 149, 151, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pantone_veri_peri = Color<_TypeChar>(102, 103, 171, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_maroon = Color<_TypeChar>(128, 0, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_navy = Color<_TypeChar>(0, 0, 128, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_forest_green = Color<_TypeChar>(34, 139, 34, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_olive = Color<_TypeChar>(128, 128, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_teal = Color<_TypeChar>(0, 128, 128, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_fuchsia = Color<_TypeChar>(255, 0, 255, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_web_safe_aqua = Color<_TypeChar>(0, 255, 255, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_rose_gold = Color<_TypeChar>(183, 110, 121, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_champagne = Color<_TypeChar>(247, 231, 206, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_lavender = Color<_TypeChar>(230, 230, 250, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_charcoal = Color<_TypeChar>(54, 69, 79, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_mint_green = Color<_TypeChar>(152, 255, 152, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_peach = Color<_TypeChar>(255, 218, 185, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_sky_blue = Color<_TypeChar>(135, 206, 235, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_lemon_chiffon = Color<_TypeChar>(255, 250, 205, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_golden_rod = Color<_TypeChar>(218, 165, 32, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_royal_blue = Color<_TypeChar>(65, 105, 225, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_midnight_blue = Color<_TypeChar>(25, 25, 112, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_forest_green = Color<_TypeChar>(34, 139, 34, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_sea_green = Color<_TypeChar>(46, 139, 87, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_dodger_blue = Color<_TypeChar>(30, 144, 255, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_firebrick = Color<_TypeChar>(178, 34, 34, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_indian_red = Color<_TypeChar>(205, 92, 92, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_hot_pink = Color<_TypeChar>(255, 105, 180, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_deep_sky_blue = Color<_TypeChar>(0, 191, 255, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_medium_violet_red = Color<_TypeChar>(199, 21, 133, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_deep_pink = Color<_TypeChar>(255, 20, 147, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_lime_green = Color<_TypeChar>(50, 205, 50, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pale_turquoise = Color<_TypeChar>(175, 238, 238, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_light_coral = Color<_TypeChar>(240, 128, 128, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_light_sea_green = Color<_TypeChar>(32, 178, 170, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_pale_violet_red = Color<_TypeChar>(219, 112, 147, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_thistle = Color<_TypeChar>(216, 191, 216, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_sienna = Color<_TypeChar>(160, 82, 45, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_peru = Color<_TypeChar>(205, 133, 63, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_turquoise = Color<_TypeChar>(64, 224, 208, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_steel_blue = Color<_TypeChar>(70, 130, 180, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_burly_wood = Color<_TypeChar>(222, 184, 135, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cadet_blue = Color<_TypeChar>(95, 158, 160, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_salmon = Color<_TypeChar>(250, 128, 114, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_dark_olive_green = Color<_TypeChar>(85, 107, 47, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_dark_orange = Color<_TypeChar>(255, 140, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_golden_yellow = Color<_TypeChar>(255, 223, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_vivid_tangerine = Color<_TypeChar>(255, 160, 137, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_amethyst = Color<_TypeChar>(153, 102, 204, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_raspberry = Color<_TypeChar>(227, 11, 92, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_electric_lime = Color<_TypeChar>(204, 255, 0, ColorType::BG);
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_neon_carrot = Color<_TypeChar>(255, 163, 67, ColorType::BG);

    
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_burnt_sienna = Color<_TypeChar>(233, 116, 81, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ultramarine_blue = Color<_TypeChar>(18, 10, 143, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_vermilion = Color<_TypeChar>(227, 66, 52, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_ochre = Color<_TypeChar>(204, 119, 34, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_phthalo_green = Color<_TypeChar>(18, 53, 36, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cerulean_blue = Color<_TypeChar>(42, 82, 190, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_alizarin_crimson = Color<_TypeChar>(227, 38, 54, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cadmium_yellow = Color<_TypeChar>(255, 246, 0, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cobalt_blue = Color<_TypeChar>(0, 71, 171, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_indigo = Color<_TypeChar>(75, 0, 130, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_viridian = Color<_TypeChar>(64, 130, 109, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_titanium_white = Color<_TypeChar>(252, 252, 252, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_paynes_gray = Color<_TypeChar>(83, 104, 120, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_prussian_blue = Color<_TypeChar>(0, 49, 83, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_carmine = Color<_TypeChar>(150, 0, 24, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_lapis_lazuli = Color<_TypeChar>(38, 97, 156, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_rose_madder = Color<_TypeChar>(227, 130, 130, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_emerald_green = Color<_TypeChar>(80, 200, 120, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_sap_green = Color<_TypeChar>(80, 128, 70, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_buff = Color<_TypeChar>(240, 220, 130, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_mars_violet = Color<_TypeChar>(150, 75, 108, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_yellow_ochre = Color<_TypeChar>(221, 176, 0, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cobalt_turquoise = Color<_TypeChar>(72, 191, 145, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_manganese_blue = Color<_TypeChar>(3, 169, 244, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_quinacridone_magenta = Color<_TypeChar>(142, 58, 89, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_indian_yellow = Color<_TypeChar>(227, 168, 87, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_naples_yellow = Color<_TypeChar>(250, 218, 94, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_venetian_red = Color<_TypeChar>(200, 8, 21, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_smalt = Color<_TypeChar>(0, 51, 153, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_lavender_blush = Color<_TypeChar>(255, 240, 245, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_sepia = Color<_TypeChar>(112, 66, 20, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_malachite_green = Color<_TypeChar>(11, 218, 81, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_venetian_blue = Color<_TypeChar>(60, 100, 160, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_caput_mortuum = Color<_TypeChar>(89, 39, 32, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_verdigris = Color<_TypeChar>(67, 179, 174, ColorType::BG); 
    template<typename _TypeChar = CHAR>
    inline const Color<_TypeChar> bg_cobalt_violet = Color<_TypeChar>(145, 33, 158, ColorType::BG); 
}


#endif 
